### PR TITLE
parse_map improvements

### PR DESCRIPTION
**Pull request by mrosack**
I've got this running now in a lambda creating images for PYDT turns as they're submitted.  I ran into a couple issues with files that would die in the parse_map helper, here's the workarounds I implemented to handle those files:

- Looking for MOD_TITLE and then the gzip header didn't seem to be reliable enough, but a longer search string seems to handle all the files i've seen so far
- On non-standard maps the mapsizedata wouldn't always find a match, but i think i've found a way to get the width of the map correctly from other areas in the data.

### CODE REVIEW

**Comment by rcannood** [comment]
Thanks for opening a PR with improvements :)

---

> I've got this running now in a lambda creating images for PYDT turns as they're submitted.

Wow, that's amazing! Is it your intention to show the post-game video at the end of a game?

---

>  I ran into a couple issues with files that would die in the parse_map helper, here's the workarounds I implemented to handle those files:
> Looking for MOD_TITLE and then the gzip header didn't seem to be reliable enough, but a longer search string seems to handle all the files i've seen so far
> On non-standard maps the mapsizedata wouldn't always find a match, but i think i've found a way to get the width of the map correctly from other areas in the data.

I should add a unit test to the components to make sure that the components actually work. If that's okay, I'll do that in the main branch and merge the changes to this PR before accepting the PR.

---

Did you manage to run the components locally using the command shown below?

```bash
viash run src/civ6_save_renderer/parse_map/config.vsh.yaml -- \
  --input data/AutoSave_0158.Civ6Save \
  --output map_0158.tsv
```

**Comment by mrosack** [comment]
> Is it your intention to show the post-game video at the end of a game?

Exactly, haven't done that part yet, but yeah, run the final step in a different lambda when the game completes.

> I should add a unit test to the components to make sure that the components actually work. If that's okay, I'll do that in the main branch and merge the changes to this PR before accepting the PR.

Yeah, sure!
 
> Did you manage to run the components locally using the command shown below?
> 
> ```shell
> viash run src/civ6_save_renderer/parse_map/config.vsh.yaml -- \
>   --input data/AutoSave_0158.Civ6Save \
>   --output map_0158.tsv
> ```

I'm precompiling the scripts when I'm building the docker image, and then I call the native target directory scripts directly if that makes sense.  The node script I'm using to run things in the lambda is here: https://github.com/pydt/api/blob/master/_docker/civ6_pipeline/node_handler/index.js and dockerfile: https://github.com/pydt/api/blob/master/_docker/civ6_pipeline/Dockerfile.imageGeneration

**Comment by mrosack** [comment]
Just FYI, I've also added some code in my repo to handle civs that aren't specified in the leaders dataframe in the R civ6saves library.  Especially now with all the leader passes there were quite a few leaders not showing up.

**Comment by rcannood** [comment]
Apologies for the late response, I missed your last two messages! Let me pick up this PR again :)

**Comment by mrosack** [comment]
No problem - I'm still working through some edge cases now that I've got a lot more sample data, hopefully I'll have all the kinks out soon...

**Comment by rcannood** [comment]
> Just FYI, I've also added some code in my repo to handle civs that aren't specified in the leaders dataframe in the R civ6saves library. Especially now with all the leader passes there were quite a few leaders not showing up.

That's a good idea! :) 

I also shared this google drive document with you, which is the source document for linking the leaders with their "proper" colours.

**Comment by rcannood** [comment]
Alright, I added tests to parse_header, parse_map and plot_map. Could you update the PR by merging upstream/main into your branch?

**Comment by rcannood** [comment]
> Just FYI, I've also added some code in my repo to handle civs that aren't specified in the leaders dataframe in the R civ6saves library. Especially now with all the leader passes there were quite a few leaders not showing up.

That's a good idea! :) 

---

> I'm precompiling the scripts when I'm building the docker image, and then I call the native target directory scripts directly if that makes sense. The node script I'm using to run things in the lambda is here: https://github.com/pydt/api/blob/master/_docker/civ6_pipeline/node_handler/index.js and dockerfile: https://github.com/pydt/api/blob/master/_docker/civ6_pipeline/Dockerfile.imageGeneration

Sure, that's also a way of doing it :+1:

---

Alright, I added tests to parse_header, parse_map and plot_map. Could you update the PR by merging upstream/main into your branch?

---

I also shared this [google drive](https://docs.google.com/spreadsheets/d/1bOlgW25zpWOUTPcPcNDbfpXK5f90J2BBaBuzwypABQs/edit#gid=1098417044) document with you, which is the source document for linking the leaders with their "proper" colours. I'd be happy to rebuild the civ6saves package whenever the information in the google document is updated.

**Comment by mrosack** [comment]
OK, merged my branch with yours - I'm going to open a new issue that maybe you can help with, I'm seeing a lot of tearing in some save files and I'm not quite sure what's happening, might be mod related.  My hunch is that it's not a quick fix, though.

**Pull request merged**
