### PR TITLE
Fix Tearing Issues

### PR DESCRIPTION
**Pull request by mrosack**
Not sure if you only want to take the second commit that keeps the scan in sync as I think that's the real win here, not sure how much the first commit really helps (it fixed that one file but made another file worse)

### CODE REVIEW

**Comment by rcannood** [comment]
LGTM! Would you like this to be merged already?

**Comment by mrosack** [comment]
Yeah, everything in here is pretty well tested and in production at PYDT, should be good to go!

**Comment by rcannood** [comment]
Hmm, unfortunately, the `plot_map` component seems to be broken

**Comment by mrosack** [comment]
I think it might be good now, I added stringr to the cran list, that just worked in my custom docker image but i guess it makes sense that it'd need to be specified here.

**Comment by rcannood** [comment]
LGTM!

**Pull request merged**
